# Generated by Django 5.2.5 on 2025-09-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyurvedhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('entry_id', models.IntegerField()),
                ('medical_code', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=255)),
                ('short_definition', models.TextField(blank=True, null=True)),
                ('long_definition', models.TextField(blank=True, null=True)),
                ('diacritical_term', models.CharField(blank=True, max_length=255, null=True)),
                ('devanagari_term', models.CharField(blank=True, max_length=255, null=True)),
                ('ontology_branches', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ayurvedha_terms',
            },
        ),
        migrations.CreateModel(
            name='SiddhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('entry_id', models.IntegerField()),
                ('medical_code', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=255)),
                ('short_definition', models.TextField(blank=True, null=True)),
                ('long_definition', models.TextField(blank=True, null=True)),
                ('tamil_term', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'siddha_terms',
            },
        ),
        migrations.CreateModel(
            name='UnaniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('entry_id', models.IntegerField()),
                ('medical_code', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=255)),
                ('short_definition', models.TextField(blank=True, null=True)),
                ('long_definition', models.TextField(blank=True, null=True)),
                ('arabic_term', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'unani_terms',
            },
        ),
    ]
