# Generated by Django 5.2.5 on 2025-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayurvedhamodel',
            old_name='medical_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='ayurvedhamodel',
            old_name='long_definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ayurvedhamodel',
            old_name='devanagari_term',
            new_name='diacritical_name',
        ),
        migrations.RenameField(
            model_name='ayurvedhamodel',
            old_name='diacritical_term',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='siddhamodel',
            old_name='medical_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='siddhamodel',
            old_name='long_definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='siddhamodel',
            old_name='tamil_term',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='unanimodel',
            old_name='arabic_term',
            new_name='arabic_name',
        ),
        migrations.RenameField(
            model_name='unanimodel',
            old_name='medical_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='unanimodel',
            old_name='long_definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='unanimodel',
            old_name='short_definition',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='ayurvedhamodel',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='ayurvedhamodel',
            name='ontology_branches',
        ),
        migrations.RemoveField(
            model_name='ayurvedhamodel',
            name='short_definition',
        ),
        migrations.RemoveField(
            model_name='ayurvedhamodel',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='ayurvedhamodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='siddhamodel',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='siddhamodel',
            name='short_definition',
        ),
        migrations.RemoveField(
            model_name='siddhamodel',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='siddhamodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='unanimodel',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='unanimodel',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='unanimodel',
            name='term',
        ),
        migrations.AddField(
            model_name='ayurvedhamodel',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siddhamodel',
            name='romanized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siddhamodel',
            name='tamil_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unanimodel',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unanimodel',
            name='romanized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='ayurvedhamodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='siddhamodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='unanimodel',
            table=None,
        ),
    ]
