# Generated by Django 5.2.5 on 2025-09-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0002_rename_medical_code_ayurvedhamodel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDClassKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICD11Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_uri', models.URLField(max_length=500, unique=True)),
                ('linearization_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('depth_in_kind', models.PositiveIntegerField(blank=True, null=True)),
                ('is_residual', models.BooleanField(default=False)),
                ('primary_location', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_no', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_link', models.URLField(blank=True, max_length=500, null=True)),
                ('icat_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_leaf', models.BooleanField(default=False)),
                ('no_of_non_residual_children', models.PositiveIntegerField(blank=True, null=True)),
                ('version_date', models.DateField(blank=True, null=True)),
                ('class_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminologies.icdclasskind')),
            ],
            options={
                'db_table': 'icd11_terms',
            },
        ),
    ]
