# Generated by Django 5.2.5 on 2025-09-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0003_icdclasskind_icd11term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd11term',
            name='class_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terminologies.icdclasskind'),
        ),
        migrations.AlterModelTable(
            name='icd11term',
            table=None,
        ),
    ]
