# Generated by Django 5.2.5 on 2025-09-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0004_alter_icd11term_class_kind_alter_icd11term_table'),
    ]

    operations = [
    ]
